<?php
// Automatically Generated by TestLink Installer - Fri, 24 Jul 15 08:11:52 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'root');
define('DB_PASS', '123456');
define('DB_HOST', '127.0.0.1');
define('DB_NAME', 'tpms');
define('DB_PORT', '3306');
//// add by refar
define('DB_TABLE_PREFIX', '');
define('DB_CHARSET', 'utf8');

define('JRDB_USER', 'root');
define('JRDB_PASS', 'root');
define('JRDB_HOST', '172.30.52.29');
define('JRDB_NAME', 'jiradb');
define('PMDB_NAME', 'pm'); // pm db name
